### ISSUE TITLE
Feature Request: Support for Comfy or Comfy Max within HA app

### ISSUE THREAD

**Issue by smcotter** [bodyscape/cielo_home#54]
Wondering if you've looked at supporting Comfy or Comfy Max within the the HA app. Not at all sure how i can help with this, but I'd be happy to assist in any way.

**Comment by bodyscape** [comment]
Not in the short term. Maybe if there are more requests like yours.

**Comment by icepuente** [comment]
@bodyscape here is another request :). Otherwise I am going to attempt to add it and open an MR.

**Comment by bodyscape** [comment]
If you want!! :) but i check and this call is not build the same way of the others. So it's more complicated.

**Comment by josheharvey** [comment]
Add me as a 3rd on this request 🙏

**Comment by asrrin29** [comment]
Adding another request please!  Just recently found out my Cielo device defaults to using my HVAC's built in temp sensor rather than the one on the Cielo device, and Comfy is the only way for it to bypass the built in sensor.  In the meantime, I can't automate with HA and have to use the remote's "Follow Me" to get down to the correct temps.

**Comment by jahnkenneth** [comment]
Add me also as number four. 
Enough requests @bodyscape ? 😀

**Comment by bodyscape** [comment]
nahh too much work sorry.. there's no quick way to do this!
