### ISSUE TITLE
Can read cielo breez plus but can't control it

### ISSUE THREAD

**Issue by halteach** [bodyscape/cielo_home#74]
The display reflects what is current state of the Breez-Plus.  However, I when I issue commands they are not "transmitted" to the device.

I am running 1.7.7

Thanks 

Hal

**Comment by theiontwo** [comment]
Same issue here.  I tried reloading the integration, restarting HA, and no luck.

**Comment by vitalmem81** [comment]
Running v1.7.5, same issue, started within the last couple of hours. Thanks.

**Comment by abanach** [comment]
I also have this issue on 1.7.7. Verified cielo app works but did not try the cielo url.

**Comment by halteach** [comment]
i can verify too that the URL is not controlling the deivce.  I was able to create some schedules on the web interface that were added to the app.

hal

**Comment by jduff001** [comment]
As of 4am EST (UTC-5) Thursday, December 5, 2024

the control has started working again.  I guess problem corrected at cielo since I didn't make any changes

**Comment by bodyscape** [comment]
Same here, it's back!

**Comment by halteach** [comment]
Yes, now working for me too.  :-) 

hal

**Comment by vaska1992** [comment]
I can also add that when i added cielo to my HA this week, it was working for a day and then stopped. First my automations did not execute. then i lost control of the dashboard buttons, but my cielo app on phone worked. I since deleted cielo from HA, and now i will try again since there are reports that it started working again.
